<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WG.AP.Core\WG.AP.Core.csproj" />
    <ProjectReference Include="..\WG.AP.DataAccess\WG.AP.DataAccess.csproj" />
    <ProjectReference Include="..\WG.AP.Email\WG.AP.Email.csproj" />
    <ProjectReference Include="..\WG.AP.Integrations.Pace\WG.AP.Integrations.Pace.csproj" />
    <ProjectReference Include="..\WG.AP.Invoice\WG.AP.Invoice.csproj" />
    <ProjectReference Include="..\WG.AP.Reporting\WG.AP.Reporting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>