<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WG.AP.Core\WG.AP.Core.csproj" />
    <ProjectReference Include="..\WG.AP.DataAccess\WG.AP.DataAccess.csproj" />
  </ItemGroup>

</Project>
