<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WG.AP.Core\WG.AP.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="NSwag.MSBuild" Version="14.2.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WG.AP.Tests" />
  </ItemGroup>

  <Target Name="GeneratePaceClient" BeforeTargets="BeforeCompile" Condition="'$(DesignTimeBuild)' != 'true' And !Exists('Generated\PaceGeneratedClient.cs')">
    <Exec Command="$(NSwagExe) run nswag.pace.dev.json" />
  </Target>

</Project>
